services:
  - type: web
    name: plant-console
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    branch: main
    rootDir: plant-console/plant-console
    envVars:
      - key: NODE_ENV
        value: production
